### ISSUE TITLE
[Bug] The label command doesn't work

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [bubkoo/label-commands#4]
## Description
I can't seem to get the label command to work for the Github action I've configured here.
All the other commands work but it does not add a label and throws no error message
This is my config
https://github.com/appsmithorg/appsmith/blob/release/.github/label-commands.yml
and the workflow file
https://github.com/appsmithorg/appsmith/blob/release/.github/workflows/label-commands.yml

**Comment by bubkoo** [comment]
@Nikhil-Nandagopal This issue was fixed in version 1.0.7. You can play with the test issue #7 , by adding/removing `feature` label.
